import networkx as nx

strong_network = nx.Graph()
network = nx.Graph()

strong_network.add_edge(1,5)
strong_network.add_edge(1,6)
strong_network.add_edge(1,11)
strong_network.add_edge(5,7)
strong_network.add_edge(5,9)
strong_network.add_edge(6,9)
strong_network.add_edge(7,11)
strong_network.add_edge(9,11)

network.add_edge(1,2)
network.add_edge(1,3)
network.add_edge(1,5)
network.add_edge(1,6)
network.add_edge(1,7)
network.add_edge(1,8)
network.add_edge(1,9)
network.add_edge(1,11)
network.add_edge(2,9)
network.add_edge(3,7)
network.add_edge(3,9)
network.add_edge(5,7)
network.add_edge(5,9)
network.add_edge(6,7)
network.add_edge(6,9)
network.add_edge(7,8)
network.add_edge(7,9)
network.add_edge(7,11)
network.add_edge(8,9)
network.add_edge(9,11)